# Generated by Django 3.0.14 on 2021-06-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hitcount',
            field=models.IntegerField(default=0),
        ),
    ]
